baseURL = 'https://looechao.com'
buildFuture = true
languageCode = 'zh-cn'
title = 'Looe Chao'
theme = "void"

[markup]
defaultMarkdownHandler = "goldmark"

[markup.highlight]
style = 'github'  # https://swapoff.org/chroma/playground/
lineNos = false
lineNumbersInTable = true

[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
[markup.goldmark.extensions]
[markup.goldmark.extensions.passthrough]
enable = true
[markup.goldmark.extensions.passthrough.delimiters]
block = [['\[', '\]'], ['$$', '$$']]
inline = [['\(', '\)']]

[pagination]
pagerSize = 10

[params]
author = "looechao"
description = "looechao's blog."
favicon = "/images/favicon.png"
images = ["/images/favicon.png"]

[params.profile]
avatar = "https://static.looechao.com/profile/profile-purple.png/profile.png"
bio = "looechao"
favicon = "/images/favicon.png"
name = "Looe"

[params.social]
email = "lu.chao.personal@gmail.com"
github = "https://www.github.com/looechao"
rss = "/posts/index.xml"

[menus]
[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Builds'
pageRef = '/builds'
weight = 30

[[menus.main]]
name = 'Reads'
pageRef = '/reads'
weight = 35

[[menus.main]]
name = 'Search'
pageRef = '/tags'
weight = 40

[frontmatter]
## lastmod = ["lastmod", ":fileModTime", ":default"]

[services]
[services.googleAnalytics]
id = 'G-9W970VLJ6X'

[params.giscus]
enable = true
repo = "looechao/hugo-comments"
repo_id = "R_kgDOLbUd7g"
category = "Announcements"
category_id = "DIC_kwDOLbUd7s4Cum0P"
mapping = "pathname"
reactions_enabled = true
emit_metadata = false
theme = "light"
lang = "en"

[module]
[[module.mounts]]
  source = 'content'
  target = 'content'
  excludeFiles = ['_templates/**']
